### ISSUE TITLE
wrong recursion detection in com.mercateo.common.rest.schemagen.SchemaPropertyGenerator.getUnwrappedFieldsMap

### ISSUE THREAD

**Issue by ReneMazala** [Mercateo/rest-schemagen#58]
If a class A has multiple fields of class B and the fields are annotated with `@JsonUnwrapped`
(with different "prefix"-attribute), then the above method throws an IllegalStateException with the message "recursion detected while unwrapping field ...".

But, this is no recursion.

Example:

```
@Value
public class A {
    @JsonUnwrapped(prefix="b1.")
    private final B b1;

    @JsonUnwrapped(prefix="b2.")
    private final B b2;
}

```
The method detects class B for field b1 first and adds it to the `unwrappedTypes` HashSet without problems. Field b2 having the same class will result in this exception.

**Comment by wuan** [comment]
We do currently not support `prefix`or `suffix` parameters from `@JsonUnwrapped`. So you will get an exeption because of colliding field names even after fixing the first problem.
We would have to add an abstraction for fields which may be a bigger change. Maybe it is easier to add this feature to Mercateo/json-schema.

**Comment by wuan** [comment]
Updated `json-schema` to be able to handle annotation based rules to modify property names.
See https://github.com/Mercateo/json-schema/pull/13
